# Generated by Django 3.0 on 2020-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmessage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
