# Generated by Django 3.0 on 2020-03-11 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_emailconfirm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConfirm',
            new_name='EmailConfirmed',
        ),
    ]
